# Generated by Django 5.1.15 on 2026-08-24 02:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_type", models.CharField(blank=True, max_length=30)),
                ("target_url", models.URLField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("error", "エラー"),
                            ("timeout", "タイムアウト"),
                            ("skipped_robots", "robots.txtにより除外"),
                            ("skipped_rate_limit", "レート制御により待機"),
                            ("skipped_circuit_open", "連続失敗によりスキップ"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "http_status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crawl_logs",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "クロールログ",
                "verbose_name_plural": "クロールログ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchQueryTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "query_suffix",
                    models.CharField(
                        blank=True, help_text="空欄なら社名のみで検索", max_length=100
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_templates",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "検索クエリテンプレート",
                "verbose_name_plural": "検索クエリテンプレート",
            },
        ),
        migrations.CreateModel(
            name="WebDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("official_hp", "企業公式HP"),
                            ("ir", "IR"),
                            ("official_recruit", "公式採用ページ"),
                            ("official_press", "公式プレスリリース"),
                            ("industry_media", "業界メディア"),
                            ("other_web", "その他Web記事"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("url", models.URLField(max_length=1000)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("first_detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("raw_text", models.TextField(blank=True)),
                ("matched_keywords", models.JSONField(blank=True, default=list)),
                ("keyword_score", models.PositiveSmallIntegerField(default=0)),
                ("source_score", models.PositiveSmallIntegerField(default=0)),
                ("freshness_score", models.PositiveSmallIntegerField(default=0)),
                ("total_score", models.PositiveSmallIntegerField(default=0)),
                ("notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_documents",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "検知情報",
                "verbose_name_plural": "検知情報",
                "ordering": ["-first_detected_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("useful", "役に立った"),
                            ("not_useful", "不要だった"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "web_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_entries",
                        to="intel.webdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "フィードバック",
                "verbose_name_plural": "フィードバック",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("alert", "営業機会アラート（80点以上）"),
                            ("watch", "要チェック（60〜79点）"),
                            ("history", "履歴（59点以下）"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="companies.company",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="accounts.organization",
                    ),
                ),
                (
                    "web_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert",
                        to="intel.webdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "アラート",
                "verbose_name_plural": "アラート",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchKeyword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("keyword", models.CharField(max_length=50)),
                ("score", models.PositiveSmallIntegerField()),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_keywords",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "監視キーワード",
                "verbose_name_plural": "監視キーワード",
                "ordering": ["-score"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "keyword"), name="uniq_org_keyword"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceTypeScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("official_hp", "企業公式HP"),
                            ("ir", "IR"),
                            ("official_recruit", "公式採用ページ"),
                            ("official_press", "公式プレスリリース"),
                            ("industry_media", "業界メディア"),
                            ("other_web", "その他Web記事"),
                        ],
                        max_length=30,
                    ),
                ),
                ("score_bonus", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_type_scores",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "情報ソース加点",
                "verbose_name_plural": "情報ソース加点",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "source_type"),
                        name="uniq_org_source_type",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="webdocument",
            constraint=models.UniqueConstraint(
                fields=("company", "url"), name="uniq_company_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.UniqueConstraint(
                fields=("web_document", "user"), name="uniq_doc_user_feedback"
            ),
        ),
    ]
