# Generated by Django 5.1.15 on 2026-08-24 02:56

import accounts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="会社名"),
                ),
                (
                    "own_website_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="自社HP URL"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("free", "FREE"), ("pro", "PRO")],
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "pro_ai_quota_monthly",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "契約組織",
                "verbose_name_plural": "契約組織",
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notify_email",
                    models.EmailField(
                        max_length=254, verbose_name="通知先メールアドレス"
                    ),
                ),
                (
                    "alert_threshold_score",
                    models.PositiveSmallIntegerField(
                        default=80, verbose_name="メール通知する最低スコア"
                    ),
                ),
                (
                    "watch_threshold_score",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="要チェック表示の最低スコア"
                    ),
                ),
                (
                    "notify_frequency",
                    models.CharField(
                        choices=[
                            ("instant", "即時通知"),
                            ("daily", "1日1回まとめ（未実装）"),
                            ("weekly", "週1回まとめ（未実装）"),
                        ],
                        default="instant",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知設定",
                "verbose_name_plural": "通知設定",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="担当者名")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "管理者")], default="admin", max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="accounts.organization",
                        verbose_name="所属組織",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー",
                "verbose_name_plural": "ユーザー",
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
    ]
