# Generated by Django 5.1.15 on 2026-08-24 02:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CsvImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("column_mapping", models.JSONField(blank=True, default=dict)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("success_rows", models.PositiveIntegerField(default=0)),
                ("duplicate_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "処理中"),
                            ("completed", "完了"),
                            ("failed", "失敗"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csv_import_batches",
                        to="accounts.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="csv_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CSV登録履歴",
                "verbose_name_plural": "CSV登録履歴",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CsvImportRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "result_status",
                    models.CharField(
                        choices=[
                            ("success", "登録成功"),
                            ("duplicate_skipped", "重複のためスキップ"),
                            ("duplicate_updated", "重複のため更新"),
                            ("error", "エラー"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="companies.csvimportbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "CSV取込行",
                "verbose_name_plural": "CSV取込行",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="企業名"),
                ),
                ("hp_url", models.URLField(max_length=500, verbose_name="企業HP URL")),
                (
                    "domain",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="正規化ドメイン"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("lost", "失注"),
                            ("past_deal", "過去取引"),
                            ("inactive", "長期未接触"),
                            ("prospect", "営業候補"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="区分",
                    ),
                ),
                (
                    "past_proposed_product",
                    models.TextField(blank=True, verbose_name="過去提案商材"),
                ),
                ("lost_reason", models.TextField(blank=True, verbose_name="失注理由")),
                (
                    "last_contact_date",
                    models.DateField(blank=True, null=True, verbose_name="最終接触日"),
                ),
                (
                    "assigned_rep",
                    models.CharField(blank=True, max_length=100, verbose_name="担当者"),
                ),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "monitoring_enabled",
                    models.BooleanField(default=True, verbose_name="監視ON/OFF"),
                ),
                (
                    "scan_interval_days",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="監視間隔日数"
                    ),
                ),
                (
                    "last_scanned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="直近スキャン日時"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "監視対象企業",
                "verbose_name_plural": "監視対象企業",
                "indexes": [
                    models.Index(
                        fields=["organization", "monitoring_enabled"],
                        name="companies_c_organiz_8853ca_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "domain"), name="uniq_org_domain"
                    )
                ],
            },
        ),
    ]
